// ui/src/App.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/core";
  import Controls from "./lib/Controls.svelte";

  type Data = {
    data: number[];
    guassian: number[];
    min: number;
    max: number;
    mean: number;
    stdev: number;
  };

  let data = $state<Data>({
    data: [],
    guassian: [],
    min: 0,
    max: 0,
    mean: 0,
    stdev: 0,
  });

  const handleClick = (cmd: string) => {
    invoke<Data>("run_command", { command: cmd || "" }).then((new_data) => {
      data = new_data;
    });
  };

  $effect(() => {
    $inspect(data);
  });
</script>

<main>
  <div class="histogram"></div>
  <Controls onclick={handleClick} />
</main>

<style>
  main {
    display: flex;
    flex-direction: column;
    gap: 5px;
    height: 100vh;
  }

  .histogram {
    background-color: #ccc;
    flex-grow: 1;
  }
</style>

// app/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import Chart from "./components/Chart.vue";
import ControlButtonGroup from "./components/ControlButtonGroup.vue";
import type { Histogram } from "./types";
import { invoke } from "@tauri-apps/api/core";

const histogram = ref<Histogram>();

onMounted(async () => {
  const result = await invoke<Histogram>("command", { cmd: "clear" });
  histogram.value = result;
});

function handleUpdated(data: Histogram) {
  histogram.value = data;
}
</script>

<template>
  <Chart :data="histogram" />
  <ControlButtonGroup @updated="handleUpdated" />
</template>

<style>
html,
body {
  height: 100%;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #ccc;
}

#app {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  height: 100%;
  overflow: hidden;
}
</style>
